### ISSUE TITLE
Unsure of How to Register Dimension Correctly

### ISSUE THREAD

**Issue by JamesF22293** [LudoCrypt/Extra-Dim-Api#1]
Just what the title says. I think I'm doing everything right with implementing ExtraDimApi in my mod class, overriding registerModDimensions and making a new builder, adding a biome, setting chunk gen settings, and building the ExtraDimension, then in a separate RegisterDimensions class creating a final Map to call the registerModDimensions(Map) and calling init in the dimension. Is there anything I'm missing here? Or am I just not doing it right?

**Comment by LudoCrypt** [comment]
The init isnt supposed to be called by itself, it calls automatically inside the API. Make sure you are putting the entrypoint correctly inside your fabric.mod.json to both the sky and the dimensions interfaces.
